<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MyPopup\Module'     => __DIR__ . '/src/MyPopup/Module.php',
    'MyPopup\ViewHelper' => __DIR__ . '/src/MyPopup/ViewHelper.php',
);
